#include <iostream>
#include <raylib.h>
#include <thread>

#include "./src/core/terminal/localterminal.hpp"

#include "./src/core/clock.hpp"
#include "./src/components/grid.hpp"
#include "./src/scenes/gamescene.hpp"

#include "./src/levels/factory.hpp"
#include "./src/levels/easylevel.hpp"
#include "./src/levels/mediumlevel.hpp"
#include "./src/levels/hardlevel.hpp"

#include "src/exchanger/exchanger.hpp"
#include "src/levels/level.hpp"
#include "src/formatter/formatter.hpp"

#include "src/core/joystick.hpp"

int main()
{
    /**
     * 
     * Event dispatching for Game class to further decouple and facilitate the transmission of internal properties otherwise
     * unamicable to perform so (Composition or inheritance(IExchanger like) ???)
     * Async environment for RemoteTerminal and RemoteStorages consider Disruptor for advancing purposes 
     * 
     * GET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELY
     * GET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELYGET THE FUCK OUT OF MY FACE INDEFINITELY
     * 
     * Da best of da best engineering delusionss !!! ayyyyy what a chance !!! GOOOOOOOOOOOOODD JOBBBB!!!!
     * Ayayaya what a best outcome ayyyy
     * 
     * Makin makin great decisions that were not yours ayyyyyyyyy what a genius best of da best universe society !!! the genius engineers of da world 
     * Ayyyyyyyyy, GET THE FUCK OUT OF MY FACE INDEFNITELY
     * 
     * Makin great great decisions and makin outcomes that can not be explained with reason !! THATS THE GENIUS OF DA BEST AND BEST AYYYYY
     * GET THE FUCK OUT OF MY FACE INDEFINITELY, INDEFINITELY,INDEFINITELY,INDEFINITELY,INDEFINITELY,INDEFINITELY
    */ 

    InitWindow(500, 620, "Raylib Tetris");
    SetTargetFPS(60);

    // Grid* grid = new Grid();
    // Level* level = makeLevelSingleton(2);
    // InputTerminal* terminal = new InputTerminal();   

    Grid* grid = new Grid();  
    Level* level = makeLevelSingleton(2);

    // BaseStorage storage = BaseStorage(); 
    // BaseTransformer formatter = BaseTransformer();
    // Exchanger exchanger = Exchanger(&storage, &formatter);

    Game* game = new Game(grid, level, 0);
    CommandFactory::Init(*game);

    Terminal* terminal = new LocalTerminal();
    JoyStick* joyStick = new JoyStick(terminal);

    GameScene gameScene = GameScene(game, joyStick);
    while(!WindowShouldClose())
    {
        BeginDrawing();
        gameScene.Draw();

        gameScene.Play();
        EndDrawing();
    }

    delete CommandFactory::GetInstance();
    CloseWindow();
}